"""Add payment methods and documents tables
Revision ID: 25f2b4147843
Revises: 002_add_ratings_table
Create Date: 2026-07-28 20:03:19.898567
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '25f2b4147843'
down_revision = '002_add_ratings_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_brand', sa.String(), nullable=False),
    sa.Column('last_4', sa.String(), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.alter_column('bookings', 'ride_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'bookings', 'users', ['customer_id'], ['id'])
    op.alter_column('messages', 'ride_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'message_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_ride_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'rides', ['ride_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'rides', ['ride_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['reviewee_id'], ['id'])
    op.create_foreign_key(None, 'ratings', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['reported_user_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'rides', ['ride_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'users', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_ride_id_fkey'), 'messages', 'rides', ['ride_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.alter_column('messages', 'message_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'ride_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('bookings', 'ride_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
